Case studies carousel
thomas-ayling/academy-project pull request #57
Opened 2022-12-16 12:05 UTC by MihneaDinuGL

2022-12-16 14:50 UTC, thomas-ayling requested changes
- Naming conventions in css leave room for conflicts, instead of things like 'case-study-description' maybe consider adding something like 'case-study-carousel-description' just for complete clarity

- Defining functions in useEffect isn't great, I think you can get away with defining the functions elsewhere and calling them from the useEffect.
- Relating to above, `src/components/case-studies-carousel/BodyCarousel.jsx Lines 10-12` could be removed and you should be able to change lines 14 and 17 out for something like `window.addEventListener('resize', setWindowWidth(window.innerWidth));` Either that or define watchWidth outside of the useEffect

- Try to use arrow functions instead of regular functions just because they are being used in the majority of the code at the moment.

- `src/components/case-studies-carousel/BodyCarousel.jsx Lines 24 - 34, 36-42, 44-50 and 52-62` could be moved into their own components and returned like this https://github.com/thomas-ayling/amcr-front-end/blob/dev/src/components/carousel/shared-components/CarouselCards.jsx
and then implemented like this https://github.com/thomas-ayling/amcr-front-end/blob/dev/src/components/carousel/MainCarousel.jsx (Line 38)

2022-12-19 09:59 UTC, thomas-ayling approved these changes
Changes look

2022-12-19 10:18 UTC, CSCairney-GL approved these changes

2022-12-19 14:25 UTC, sourcesmith commented on src/components/case-studies-carousel/BodyCarousel.jsx
> +  const [windowWidth, setWindowWidth] = useState(window.innerWidth);
Couple of thoughts here:

Resize listeners are a bit dated.  See https://developer.mozilla.org/en-US/docs/Web/API/ResizeObserver.  I think there are packages that will provide is a  custom hook or other approaches too.

Why is the carousel not response/styled with breakpoints(media queries)?  Actually I seem some logic around the width to with anchors but I am not quite following it, so is possibly nothing to do with layout.

2022-12-19 15:12 UTC, MihneaDinuGL commented on src/components/case-studies-carousel/BodyCarousel.jsx
> +  const [windowWidth, setWindowWidth] = useState(window.innerWidth);
Hiya, I'll have a look at the resizeobserver and implement something more modern. As for the media queries, I have that at the bottom at the css page, but I'll move it up -- is that what you mean?

2022-12-19 16:33 UTC, sourcesmith commented on src/components/case-studies-carousel/BodyCarousel.jsx
> +  const [windowWidth, setWindowWidth] = useState(window.innerWidth);
Sorry, I am trying to understand why the carousel needs the windowWidth prop.  This suggests something with layout but maybe in this case it is not.

2022-12-19 16:50 UTC, MihneaDinuGL commented on src/components/case-studies-carousel/BodyCarousel.jsx
> +  const [windowWidth, setWindowWidth] = useState(window.innerWidth);
Oh sorry! I just made it so a user can click on the image associated with each case study in the carousel and be redirected to its individual page (same as if using the 'learn more' button). 

However, I wanted to remove this feature for small screens, as users could accidentally click the images and be redirected against their wills, so I just had the windowWidth prop constantly be updated whenever the screen size is changed, and removing that feature whenever the screen gets small enough

2022-12-20 09:59 UTC, sourcesmith commented on src/components/case-studies-carousel/BodyCarousel.jsx
> +  const [windowWidth, setWindowWidth] = useState(window.innerWidth);
Okay, that makes sense.

2022-12-20 12:02 UTC, sourcesmith approved these changes

2022-12-20 12:59 UTC, merged