Case studies header carousel
thomas-ayling/academy-project pull request #90
Opened 2023-01-16 10:31 UTC by Kya-Edmeade

2023-01-16 12:22 UTC, jab-khanGL requested changes
Just looking at the changes in the MainCarousel and noticed that some of the swipe controls have gone? Might be best to look at the MainCarousel on dev to see what's different.

HomepageCarousel.css is not needed anymore as the homepage is using the MainCarousel css now. 

Also seems to be 2 Carousel Titles. It might have been misplaced.

2023-01-16 14:21 UTC, jab-khanGL approved these changes

2023-01-17 13:50 UTC, sourcesmith commented on src/components/main-carousel/MainCarousel.jsx
> +        {type.includes('header') && <CarouselTitles slides={slides} current={current} onClick={() => isLink && handleClickLink(slides.id)} classNames={classNames}/>}
An event handler should be set to a function or undefined so use the form {isLink ? () =>  handleClickLink(slides.id) : undefined} .

2023-01-18 14:04 UTC, sourcesmith approved these changes

2023-01-19 09:24 UTC, sourcesmith commented on src/components/main-carousel/MainCarousel.jsx
> +        {type.includes('header') && <CarouselTitles slides={slides} current={current} onClick={() => isLink && handleClickLink(slides.id)} classNames={classNames}/>}
This is still registering a handler when `isLink` is `false` which is pointless because the value of `isLink` will not change during that render.

2023-02-08 08:25 UTC, sourcesmith commented on src/components/main-carousel/MainCarousel.jsx
> +        {type.includes('header') && <CarouselTitles slides={slides} current={current} onClick={() => isLink && handleClickLink(slides.id):undefined} classNames={classNames}/>}
Should map to an arrow function on `isLink` being true and `undefined` otherwise.  There is no point defining an arrow function that then returns `undefined`.  `undefined` should be used to indicate that no function is set for the handler.

2023-02-15 13:55 UTC, closed without merging